# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherMobileApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherMobileApp
  pod 'Alamofire'
  pod 'AppCenter'

  target 'WeatherMobileAppTests' do
    inherit! :search_paths
    # Pods for testing
    use_frameworks!

  end

  target 'WeatherMobileAppUITests' do
    inherit! :search_paths
    # Pods for testing
    use_frameworks!
    project '../WeatherMobileApp/WeatherMobileApp'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
  end
end
