# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherMobileApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherMobileApp
  pod 'Alamofire'
  pod 'AppCenter'

  target 'WeatherMobileAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherMobileAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
