# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
  pod 'Alamofire'
end

target 'WeatherMobileApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  shared_pods
  # Pods for WeatherMobileApp
  pod 'AppCenter'

  target 'WeatherMobileAppTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

  target 'WeatherMobileAppUITests' do
    inherit! :search_paths
    # Pods for testing
    shared_pods
  end

end

